INSERT INTO TB_TYPE VALUES(1, 'Defect');
INSERT INTO TB_TYPE VALUES(2, 'Feature');
INSERT INTO TB_TYPE VALUES(3, 'Patch');

INSERT INTO TB_PRIORITY VALUES(1, 'Low');
INSERT INTO TB_PRIORITY VALUES(2, 'Normal');
INSERT INTO TB_PRIORITY VALUES(3, 'High');
INSERT INTO TB_PRIORITY VALUES(4, 'Urgent');

INSERT INTO TB_STATUS VALUES(1, 'New');
INSERT INTO TB_STATUS VALUES(2, 'Confirmed');
INSERT INTO TB_STATUS VALUES(3, 'Resolved');
INSERT INTO TB_STATUS VALUES(4, 'Closed');
INSERT INTO TB_STATUS VALUES(5, 'Reopened');
